### ISSUE TITLE
[JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by namhuynhftu** [davidzajac1/zillacode#4]
I I have done all the steps mentioned in the github and installed docker , now when i try to run the code in the local host page , im getting the below error.

`[JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.`

Please suggest ways to resolve this issue , Im not able to compile any of my code

**Comment by AHabeshi** [comment]
Same issue here unfortunately.

**Comment by davidzajac1** [comment]
@namhuynhftu @namhuynhftu I think I may have been able to fixed this.

Can you please try cloning the `dockerhub` branch like `git clone -b dockerhub https://github.com/davidzajac1/zillacode.git` and run `docker-compose up` again and see if it works?

I hosted the images for all of the containers on DockerHub so they will be pulled from there instead of built locally.

**Comment by AHabeshi** [comment]
I tried this and it works :) thank you for maintaining this very helpful project

**Comment by davidzajac1** [comment]
> I tried this and it works :) thank you for maintaining this very helpful project

Great glad it works, thanks for working with me on this issue!
